
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package MiniSQL;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TRUNCATE = 2;
  public static final int Punto = 8;
  public static final int Puntoycoma = 6;
  public static final int EOF = 0;
  public static final int Coma = 5;
  public static final int TABLE = 3;
  public static final int Identificador = 4;
  public static final int error = 1;
  public static final int GO = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TRUNCATE",
  "TABLE",
  "Identificador",
  "Coma",
  "Puntoycoma",
  "GO",
  "Punto"
  };
}

