
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Signodiv = 324;
  public static final int SQLCODE = 254;
  public static final int DECLARE = 72;
  public static final int INTEGER = 142;
  public static final int SIZE = 243;
  public static final int DATABASE = 65;
  public static final int RELATIVE = 225;
  public static final int SOME = 247;
  public static final int MONTH = 174;
  public static final int BOTH = 23;
  public static final int GO = 120;
  public static final int PIVOT = 198;
  public static final int Signomenorigual = 329;
  public static final int CLOSE = 39;
  public static final int END_EXEC = 92;
  public static final int Coma = 337;
  public static final int PAD = 206;
  public static final int USE = 302;
  public static final int MODULE = 171;
  public static final int Signomas = 321;
  public static final int DAY = 67;
  public static final int CONSTRAINT = 49;
  public static final int WRITETEXT = 314;
  public static final int BROWSE = 25;
  public static final int CONTINUE = 53;
  public static final int PROCEDURE = 208;
  public static final int OPENDATASOURCE = 185;
  public static final int WRITE = 309;
  public static final int LEVEL = 157;
  public static final int FETCH = 102;
  public static final int ZONE = 312;
  public static final int CATALOG = 32;
  public static final int INTERSECT = 143;
  public static final int TRUE = 284;
  public static final int DENY = 77;
  public static final int OFF = 176;
  public static final int DEALLOCATE = 69;
  public static final int SECTION = 238;
  public static final int FROM = 114;
  public static final int TEXTSIZE = 272;
  public static final int DUMP = 89;
  public static final int SET = 242;
  public static final int ASC = 13;
  public static final int SQLERROR = 256;
  public static final int DIAGNOSTICS = 81;
  public static final int KEY = 149;
  public static final int TIMEZONE_HOUR = 271;
  public static final int SQLCA = 252;
  public static final int RESTRICT = 224;
  public static final int FREETEXT = 111;
  public static final int GET = 117;
  public static final int OPTION = 191;
  public static final int NUMERIC = 186;
  public static final int ARE = 11;
  public static final int LINENO = 156;
  public static final int DESCRIPTOR = 80;
  public static final int SECURITYAUDIT = 248;
  public static final int NULLIF = 172;
  public static final int POSITION = 211;
  public static final int SECOND = 237;
  public static final int DECIMAL = 71;
  public static final int COUNT = 56;
  public static final int PRECISION = 201;
  public static final int NONE = 183;
  public static final int LAST = 153;
  public static final int DISCONNECT = 82;
  public static final int CURRENT_USER = 63;
  public static final int EXECUTE = 98;
  public static final int Float = 317;
  public static final int SAVE = 246;
  public static final int TRUNCATE = 283;
  public static final int Signomenos = 322;
  public static final int Signomenor = 328;
  public static final int DEFAULT = 73;
  public static final int SESSION_USER = 241;
  public static final int BY = 27;
  public static final int ComentarioLinea = 319;
  public static final int DEFERRED = 75;
  public static final int EXISTS = 99;
  public static final int ERROR = 352;
  public static final int BIT = 21;
  public static final int HAVING = 124;
  public static final int LANGUAGE = 152;
  public static final int IDENTITY_INSERT = 135;
  public static final int CURRENT_TIME = 61;
  public static final int INDEX = 131;
  public static final int THEN = 267;
  public static final int BIT_LENGTH = 22;
  public static final int AT = 15;
  public static final int EOF = 0;
  public static final int ALLOCATE = 7;
  public static final int AS = 12;
  public static final int Signoyy = 333;
  public static final int EXTRACT = 103;
  public static final int TRIGGER = 282;
  public static final int OPENROWSET = 189;
  public static final int INT = 141;
  public static final int TIMEZONE_MINUTE = 273;
  public static final int BACKUP = 18;
  public static final int Puntoycoma = 336;
  public static final int VALUES = 297;
  public static final int NEXT = 180;
  public static final int ANY = 10;
  public static final int Parentesis = 344;
  public static final int KILL = 150;
  public static final int SUBSTRING = 259;
  public static final int PUBLIC = 210;
  public static final int SEMANTICSIMILARITYDETAILSTABLE = 253;
  public static final int CASCADED = 29;
  public static final int BREAK = 24;
  public static final int PREPARE = 213;
  public static final int Parentesisapertura = 342;
  public static final int END = 91;
  public static final int ELSE = 90;
  public static final int VIEW = 301;
  public static final int PERCENT = 197;
  public static final int AND = 9;
  public static final int NCHAR = 179;
  public static final int Llavecerradura = 346;
  public static final int Signoporcentaje = 325;
  public static final int RETURN = 226;
  public static final int DBCC = 68;
  public static final int CONTAINS = 51;
  public static final int ROLLBACK = 230;
  public static final int CONNECTION = 48;
  public static final int FOREIGN = 110;
  public static final int ESCAPE = 94;
  public static final int CURSOR = 64;
  public static final int Signomult = 323;
  public static final int NATURAL = 177;
  public static final int UNPIVOT = 294;
  public static final int NONCLUSTERED = 165;
  public static final int Signonotigual = 332;
  public static final int IMMEDIATE = 128;
  public static final int RULE = 244;
  public static final int INTO = 145;
  public static final int CHARACHTER_LENGTH = 36;
  public static final int ALL = 6;
  public static final int Llaves = 347;
  public static final int LOAD = 158;
  public static final int TABLESAMPLE = 270;
  public static final int COLUMN = 44;
  public static final int Corchetecerradura = 340;
  public static final int BEGIN = 19;
  public static final int CORRESPONDING = 55;
  public static final int OPENQUERY = 188;
  public static final int LOWER = 162;
  public static final int SQLWARNING = 258;
  public static final int OCTET_LENGTH = 187;
  public static final int Punto = 338;
  public static final int UNIQUE = 286;
  public static final int GRANT = 122;
  public static final int TRY_CONVERT = 287;
  public static final int ROWS = 232;
  public static final int INTERVAL = 144;
  public static final int OPEN = 184;
  public static final int WORK = 308;
  public static final int CURRENT_DATE = 60;
  public static final int TIMESTAMP = 269;
  public static final int ALTER = 8;
  public static final int PRIVILEGES = 219;
  public static final int Corcheteapertura = 339;
  public static final int TOP = 276;
  public static final int REVOKE = 228;
  public static final int FULL = 116;
  public static final int RESTORE = 223;
  public static final int EXTERNAL = 101;
  public static final int SUM = 260;
  public static final int MIN = 168;
  public static final int OFFSES = 178;
  public static final int TEMPORARY = 266;
  public static final int ABSOLUTE = 2;
  public static final int CONVERT = 54;
  public static final int ORDER = 194;
  public static final int COMPUTE = 46;
  public static final int TO = 274;
  public static final int LIKE = 155;
  public static final int FILE = 105;
  public static final int Sharp = 349;
  public static final int REPLICATION = 221;
  public static final int Identificador = 351;
  public static final int PRIMARY = 202;
  public static final int DEFERRABLE = 74;
  public static final int FLOAT = 109;
  public static final int DOUBLE = 87;
  public static final int SEMANTICKEYPHRASETABLE = 250;
  public static final int SELECT = 239;
  public static final int VARYING = 299;
  public static final int Cadena = 318;
  public static final int CHECK = 37;
  public static final int FIRST = 107;
  public static final int TRIM = 281;
  public static final int NAMES = 175;
  public static final int INPUT = 136;
  public static final int WHERE = 305;
  public static final int SQLSTATE = 257;
  public static final int UPDATE = 290;
  public static final int BETWEEN = 20;
  public static final int Signoigual = 330;
  public static final int RAISERROR = 212;
  public static final int RECONFIGURE = 218;
  public static final int IDENTITY = 127;
  public static final int GROUP = 123;
  public static final int TRANSLATION = 280;
  public static final int USING = 295;
  public static final int TSEQUAL = 289;
  public static final int PRESERVE = 215;
  public static final int USER = 293;
  public static final int DOMAIN = 86;
  public static final int COALLITION = 43;
  public static final int SQL = 251;
  public static final int LOCAL = 160;
  public static final int TRANSLATE = 279;
  public static final int SYSTEM_USER = 263;
  public static final int VALUE = 296;
  public static final int ONLY = 192;
  public static final int EXIT = 100;
  public static final int LEADING = 154;
  public static final int Signoor = 334;
  public static final int TABLE = 265;
  public static final int SCHEMA = 234;
  public static final int error = 1;
  public static final int REVERT = 231;
  public static final int WAITFOR = 307;
  public static final int FORTRAN = 112;
  public static final int STATISTICS = 264;
  public static final int NOCHECK = 163;
  public static final int TIME = 268;
  public static final int LEFT = 151;
  public static final int OR = 193;
  public static final int ASSERTION = 14;
  public static final int PROC = 204;
  public static final int Parentesiscerradura = 343;
  public static final int WHENEVER = 304;
  public static final int ON = 182;
  public static final int CASCADE = 28;
  public static final int EXCEPTION = 96;
  public static final int CHAR = 33;
  public static final int OF = 173;
  public static final int ROWGUIDCOL = 236;
  public static final int DELETE = 76;
  public static final int UPPER = 291;
  public static final int ADD = 5;
  public static final int ADA = 4;
  public static final int Signomayorigual = 327;
  public static final int COMMIT = 45;
  public static final int CLUSTERED = 40;
  public static final int ACTION = 3;
  public static final int WHEN = 303;
  public static final int JOIN = 148;
  public static final int NULL = 169;
  public static final int MINUTE = 170;
  public static final int INNER = 134;
  public static final int TRAILING = 275;
  public static final int CONTAINSTABLE = 52;
  public static final int TRANSACTION = 277;
  public static final int NO = 181;
  public static final int Entero = 315;
  public static final int OPENXML = 190;
  public static final int FUNCTION = 119;
  public static final int PRIOR = 217;
  public static final int SPACE = 249;
  public static final int CAST = 31;
  public static final int CHAR_LENGTH = 34;
  public static final int SHUTDOWN = 262;
  public static final int INSENSITIVE = 139;
  public static final int SCROLL = 235;
  public static final int CASE = 30;
  public static final int ERRLVL = 93;
  public static final int PLAN = 199;
  public static final int UPDATETEXT = 300;
  public static final int UNION = 285;
  public static final int DROP = 88;
  public static final int DISTURBED = 85;
  public static final int MAX = 166;
  public static final int OUTPUT = 200;
  public static final int PRINT = 203;
  public static final int INDICATOR = 132;
  public static final int Signomayor = 326;
  public static final int FILLFACTOR = 106;
  public static final int GLOBAL = 118;
  public static final int PARTIAL = 207;
  public static final int GOTO = 121;
  public static final int INCLUDE = 130;
  public static final int WHILE = 311;
  public static final int SEMANTICSIMILARITYTABLE = 255;
  public static final int CONNECT = 47;
  public static final int VARCHAR = 298;
  public static final int CURRENT_TIMESTAMP = 62;
  public static final int BULK = 26;
  public static final int INITIALLY = 133;
  public static final int Boolean = 316;
  public static final int FALSE = 104;
  public static final int SESSION = 240;
  public static final int AUTHORIZATION = 16;
  public static final int EXEC = 97;
  public static final int REFERENCES = 220;
  public static final int Arroba = 348;
  public static final int Signoigualigual = 331;
  public static final int CREATE = 57;
  public static final int INSERT = 140;
  public static final int CHECKPOINT = 38;
  public static final int REAL = 222;
  public static final int ISOLATION = 147;
  public static final int READ = 214;
  public static final int SMALLINT = 245;
  public static final int Llaveapertura = 345;
  public static final int WITH = 306;
  public static final int CURRENT = 59;
  public static final int CHARACTER = 35;
  public static final int DATE = 66;
  public static final int TRAN = 278;
  public static final int DISK = 83;
  public static final int ComentarioMultiliena = 320;
  public static final int DESCRIBE = 79;
  public static final int HOLDLOCK = 125;
  public static final int OVER = 196;
  public static final int OUTER = 195;
  public static final int DESC = 78;
  public static final int DEC = 70;
  public static final int USAGE = 292;
  public static final int HOUR = 126;
  public static final int FREETEXTTABLE = 115;
  public static final int WITHINGROUP = 313;
  public static final int IS = 146;
  public static final int ROWCOUNT = 233;
  public static final int RETURNS = 227;
  public static final int IN = 129;
  public static final int OVERLAPS = 205;
  public static final int SETUSER = 261;
  public static final int Corchetes = 341;
  public static final int MERGE = 159;
  public static final int Signoadmiracion = 335;
  public static final int DISTINCT = 84;
  public static final int IF = 138;
  public static final int CONSTRAINTS = 50;
  public static final int UNKNOWN = 288;
  public static final int RIGHT = 229;
  public static final int CROSS = 58;
  public static final int NOT = 167;
  public static final int YEAR = 310;
  public static final int MATCH = 164;
  public static final int PASCAL = 209;
  public static final int IDENTITYCOL = 137;
  public static final int EXCEPT = 95;
  public static final int NATIONAL = 161;
  public static final int READTEXT = 216;
  public static final int COLLATE = 42;
  public static final int FOUND = 113;
  public static final int Sharpsharp = 350;
  public static final int AVG = 17;
  public static final int FOR = 108;
  public static final int COALESCE = 41;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ABSOLUTE",
  "ACTION",
  "ADA",
  "ADD",
  "ALL",
  "ALLOCATE",
  "ALTER",
  "AND",
  "ANY",
  "ARE",
  "AS",
  "ASC",
  "ASSERTION",
  "AT",
  "AUTHORIZATION",
  "AVG",
  "BACKUP",
  "BEGIN",
  "BETWEEN",
  "BIT",
  "BIT_LENGTH",
  "BOTH",
  "BREAK",
  "BROWSE",
  "BULK",
  "BY",
  "CASCADE",
  "CASCADED",
  "CASE",
  "CAST",
  "CATALOG",
  "CHAR",
  "CHAR_LENGTH",
  "CHARACTER",
  "CHARACHTER_LENGTH",
  "CHECK",
  "CHECKPOINT",
  "CLOSE",
  "CLUSTERED",
  "COALESCE",
  "COLLATE",
  "COALLITION",
  "COLUMN",
  "COMMIT",
  "COMPUTE",
  "CONNECT",
  "CONNECTION",
  "CONSTRAINT",
  "CONSTRAINTS",
  "CONTAINS",
  "CONTAINSTABLE",
  "CONTINUE",
  "CONVERT",
  "CORRESPONDING",
  "COUNT",
  "CREATE",
  "CROSS",
  "CURRENT",
  "CURRENT_DATE",
  "CURRENT_TIME",
  "CURRENT_TIMESTAMP",
  "CURRENT_USER",
  "CURSOR",
  "DATABASE",
  "DATE",
  "DAY",
  "DBCC",
  "DEALLOCATE",
  "DEC",
  "DECIMAL",
  "DECLARE",
  "DEFAULT",
  "DEFERRABLE",
  "DEFERRED",
  "DELETE",
  "DENY",
  "DESC",
  "DESCRIBE",
  "DESCRIPTOR",
  "DIAGNOSTICS",
  "DISCONNECT",
  "DISK",
  "DISTINCT",
  "DISTURBED",
  "DOMAIN",
  "DOUBLE",
  "DROP",
  "DUMP",
  "ELSE",
  "END",
  "END_EXEC",
  "ERRLVL",
  "ESCAPE",
  "EXCEPT",
  "EXCEPTION",
  "EXEC",
  "EXECUTE",
  "EXISTS",
  "EXIT",
  "EXTERNAL",
  "FETCH",
  "EXTRACT",
  "FALSE",
  "FILE",
  "FILLFACTOR",
  "FIRST",
  "FOR",
  "FLOAT",
  "FOREIGN",
  "FREETEXT",
  "FORTRAN",
  "FOUND",
  "FROM",
  "FREETEXTTABLE",
  "FULL",
  "GET",
  "GLOBAL",
  "FUNCTION",
  "GO",
  "GOTO",
  "GRANT",
  "GROUP",
  "HAVING",
  "HOLDLOCK",
  "HOUR",
  "IDENTITY",
  "IMMEDIATE",
  "IN",
  "INCLUDE",
  "INDEX",
  "INDICATOR",
  "INITIALLY",
  "INNER",
  "IDENTITY_INSERT",
  "INPUT",
  "IDENTITYCOL",
  "IF",
  "INSENSITIVE",
  "INSERT",
  "INT",
  "INTEGER",
  "INTERSECT",
  "INTERVAL",
  "INTO",
  "IS",
  "ISOLATION",
  "JOIN",
  "KEY",
  "KILL",
  "LEFT",
  "LANGUAGE",
  "LAST",
  "LEADING",
  "LIKE",
  "LINENO",
  "LEVEL",
  "LOAD",
  "MERGE",
  "LOCAL",
  "NATIONAL",
  "LOWER",
  "NOCHECK",
  "MATCH",
  "NONCLUSTERED",
  "MAX",
  "NOT",
  "MIN",
  "NULL",
  "MINUTE",
  "MODULE",
  "NULLIF",
  "OF",
  "MONTH",
  "NAMES",
  "OFF",
  "NATURAL",
  "OFFSES",
  "NCHAR",
  "NEXT",
  "NO",
  "ON",
  "NONE",
  "OPEN",
  "OPENDATASOURCE",
  "NUMERIC",
  "OCTET_LENGTH",
  "OPENQUERY",
  "OPENROWSET",
  "OPENXML",
  "OPTION",
  "ONLY",
  "OR",
  "ORDER",
  "OUTER",
  "OVER",
  "PERCENT",
  "PIVOT",
  "PLAN",
  "OUTPUT",
  "PRECISION",
  "PRIMARY",
  "PRINT",
  "PROC",
  "OVERLAPS",
  "PAD",
  "PARTIAL",
  "PROCEDURE",
  "PASCAL",
  "PUBLIC",
  "POSITION",
  "RAISERROR",
  "PREPARE",
  "READ",
  "PRESERVE",
  "READTEXT",
  "PRIOR",
  "RECONFIGURE",
  "PRIVILEGES",
  "REFERENCES",
  "REPLICATION",
  "REAL",
  "RESTORE",
  "RESTRICT",
  "RELATIVE",
  "RETURN",
  "RETURNS",
  "REVOKE",
  "RIGHT",
  "ROLLBACK",
  "REVERT",
  "ROWS",
  "ROWCOUNT",
  "SCHEMA",
  "SCROLL",
  "ROWGUIDCOL",
  "SECOND",
  "SECTION",
  "SELECT",
  "SESSION",
  "SESSION_USER",
  "SET",
  "SIZE",
  "RULE",
  "SMALLINT",
  "SAVE",
  "SOME",
  "SECURITYAUDIT",
  "SPACE",
  "SEMANTICKEYPHRASETABLE",
  "SQL",
  "SQLCA",
  "SEMANTICSIMILARITYDETAILSTABLE",
  "SQLCODE",
  "SEMANTICSIMILARITYTABLE",
  "SQLERROR",
  "SQLSTATE",
  "SQLWARNING",
  "SUBSTRING",
  "SUM",
  "SETUSER",
  "SHUTDOWN",
  "SYSTEM_USER",
  "STATISTICS",
  "TABLE",
  "TEMPORARY",
  "THEN",
  "TIME",
  "TIMESTAMP",
  "TABLESAMPLE",
  "TIMEZONE_HOUR",
  "TEXTSIZE",
  "TIMEZONE_MINUTE",
  "TO",
  "TRAILING",
  "TOP",
  "TRANSACTION",
  "TRAN",
  "TRANSLATE",
  "TRANSLATION",
  "TRIM",
  "TRIGGER",
  "TRUNCATE",
  "TRUE",
  "UNION",
  "UNIQUE",
  "TRY_CONVERT",
  "UNKNOWN",
  "TSEQUAL",
  "UPDATE",
  "UPPER",
  "USAGE",
  "USER",
  "UNPIVOT",
  "USING",
  "VALUE",
  "VALUES",
  "VARCHAR",
  "VARYING",
  "UPDATETEXT",
  "VIEW",
  "USE",
  "WHEN",
  "WHENEVER",
  "WHERE",
  "WITH",
  "WAITFOR",
  "WORK",
  "WRITE",
  "YEAR",
  "WHILE",
  "ZONE",
  "WITHINGROUP",
  "WRITETEXT",
  "Entero",
  "Boolean",
  "Float",
  "Cadena",
  "ComentarioLinea",
  "ComentarioMultiliena",
  "Signomas",
  "Signomenos",
  "Signomult",
  "Signodiv",
  "Signoporcentaje",
  "Signomayor",
  "Signomayorigual",
  "Signomenor",
  "Signomenorigual",
  "Signoigual",
  "Signoigualigual",
  "Signonotigual",
  "Signoyy",
  "Signoor",
  "Signoadmiracion",
  "Puntoycoma",
  "Coma",
  "Punto",
  "Corcheteapertura",
  "Corchetecerradura",
  "Corchetes",
  "Parentesisapertura",
  "Parentesiscerradura",
  "Parentesis",
  "Llaveapertura",
  "Llavecerradura",
  "Llaves",
  "Arroba",
  "Sharp",
  "Sharpsharp",
  "Identificador",
  "ERROR"
  };
}

